na-trium-144/falling-nikochan

app/chartFormat/chart.ts, app/common/button.tsx, app/common/input.tsx, app/edit/[cid]/metaTab.tsx, app/edit/[cid]/page.tsx, app/main/chartList.tsx, app/main/edit/page.tsx, app/main/play/page.tsx
- editメニューのUIを改善、新規作成の処理を変更
- metaタブのUIを改善
=> edit画面のui改善

app/api/chartFile/[cid]/route.ts, app/api/newChartFile/route.ts, app/api/seqFile/[cid]/route.ts, app/chartFormat/chart.ts, app/chartFormat/command.ts, app/chartFormat/legacy/chart1.ts, app/chartFormat/seq.ts, app/common/button.tsx, app/common/input.tsx, app/edit/[cid]/dragHandle.tsx, app/edit/[cid]/fallingWindow.tsx, app/edit/[cid]/metaTab.tsx, app/edit/[cid]/noteTab.tsx, app/edit/[cid]/page.tsx, app/edit/[cid]/timeBar.tsx, app/edit/[cid]/timingTab.tsx, app/main/edit/page.tsx
* x, vx, vy, ayが整数値になるようにした
* (xは-5〜5で vx, vy, ayはいままでの4/bpm倍)
* editモードでマウス操作を改善
* マウスドラッグでxを動かし、shift押しながらでvxとvy, ctrl押しながらでayを動かす
* shift+左右きーで16step移動
* 未使用だっtimeScaleパラメータを削除し、scaleChangeを追加、編集可能にした
* 全ノーツに反映される速度変化
=> 音符速度の処理を一新

app/edit/[cid]/metaTab.tsx
=> 譜面ファイルの拡張子変更、保存時にパスワードを削除

app/edit/[cid]/metaTab.tsx, app/edit/[cid]/page.tsx, app/play/messageBox.tsx, app/play/page.tsx, app/play/session.ts
- edit時のsessionIdを固定
- 編集時のメッセージ
=> 編集時のsessionIdを固定

app/chartFormat/difficulty.ts, app/chartFormat/lua/exec.ts, app/edit/[cid]/levelTab.tsx, app/edit/[cid]/metaTab.tsx, app/edit/[cid]/noteTab.tsx, app/edit/[cid]/page.tsx, app/edit/[cid]/timeBar.tsx, app/play/page.tsx, app/play/session.ts, app/play/statusBox.tsx, app/share/[cid]/playOption.tsx
- アップロードで編集用パスワードが消えないようにした
- metaタブを開かなくてもsessionにchartの編集が反映されるようにした
- ショートカットで制限を超えて音符をおけないようにした
- unload時にsessionを削除
- edit画面でlua側からspeedを変更したとき反映されていなかったのを修正
- レベルの表示を改善、レスポンシブの修正など
=> editのバグ修正、表示修正など

app/edit/[cid]/levelTab.tsx, app/edit/[cid]/page.tsx
- levelの並べ替え機能を追加
- level選択がテストプレイsessionに反映されるようにした
=> levelの並べ替え機能追加

app/common/footer.tsx, app/main/main.tsx
* menuの遷移にアニメーションをつけてなめらかにした
* フッターのナビゲーション有無を変数ではなくcssで切り替えるようにした
=> menuの遷移をなめらかにした

app/api/dbRateLimit.ts, app/api/newChartFile/route.ts
ついでに制限を10分に変更
(同一ipから複数人がアクセスする可能性もある、その場合30分は長すぎるのではと思ったので)
=> x-forwarded-forを書き換えたら制限回避できてしまうのを修正

app/common/youtube.tsx, app/edit/[cid]/page.tsx, app/play/musicArea.tsx, app/play/page.tsx
- **モバイル表示でYouTubeを50%表示**
- **YouTube表示部分を別ファイルに分割**
- **タブレット表示のとき文字を少し大きくした**
=> YouTubeとタイトルなど表示部分の改良

app/common/box.tsx, app/common/button.tsx, app/common/loadingSlime.css, app/common/loadingSlime.tsx, app/edit/[cid]/metaTab.tsx, app/globals.css, app/main/edit/page.tsx, app/main/play/page.tsx, tsconfig.json
* Loading時にslimeがぴょんぴょんするようにした
close #27 
close #43
=> loadingSlime

app/api/fsAccess.ts
=> データを圧縮して保存

app/edit/[cid]/metaTab.tsx, app/edit/[cid]/page.tsx, app/play/session.ts, app/share/[cid]/playOption.tsx
sessionを作成するたびに過去のsessionをすべて削除するようにした。
=> sessionの管理を再度修正

app/common/rank.ts, app/main/about/[aboutIndex]/2-play.tsx, app/main/about/[aboutIndex]/3-edit.tsx, app/main/about/[aboutIndex]/4-level.tsx, app/main/about/[aboutIndex]/5-judge.tsx, app/main/about/[aboutIndex]/page.tsx, app/main/play/page.tsx
=> レベルやゲーム仕様についての説明を追加

app/api/brief/[cid]/route.ts, app/api/brief/brief.ts, app/api/chartFile/[cid]/route.ts, app/api/dbChartFile.ts, app/api/newChartFile/route.ts, app/api/seqFile/[cid]/[lvIndex]/route.ts, app/main/play/page.tsx, app/share/[cid]/page.tsx
- **サンプル譜面リストを更新**
- **briefのフェッチ時にlevelsの情報を常には含めないようにした**
=> サンプル譜面リストを更新

app/common/youtube.tsx, app/play/messageBox.tsx, app/play/page.tsx, app/play/result.tsx, app/share/[cid]/playOption.tsx
- **譜面終了・中断時にフェードアウトするようにした**
- **playをリファクタリングしたがyoutubeAPI動作しない問題は解決せず**
- **share→playで強制リロードするようにした**
- **stoppedまたはresult時にspaceでready画面に戻るようにした**
fix #9
=> play画面のYouTubeの動作を修正

app/play/page.tsx
* スタートを押さずに勝手に始まってしまうバグを修正
* YouTube埋め込みの初期音量は100で固定っぽい?
=> play画面のresetの処理を修正

app/main/edit/layout.tsx, app/main/main.tsx, app/main/play/clientPage.tsx, app/main/play/layout.tsx, app/main/play/page.tsx
googleなどのクローラが認識できるように、トップページの項目はhrefを残し、サンプル譜面一覧はサーバーサイドで生成するようにした
=> トップページのメニューとサンプル譜面のリンクをSSRで生成

CHANGELOG.md, app/common/extLink.tsx, app/common/footer.tsx, app/common/linkStyle.ts, app/edit/[cid]/metaTab.tsx, app/main/const.ts, app/main/edit/page.tsx, app/main/main.tsx, app/main/policies/page.tsx, app/main/version/layout.tsx, app/main/version/page.tsx, app/share/[cid]/playOption.tsx, next.config.mjs, package-lock.json, package.json, tailwind.config.ts
* バージョン番号を定義
* #80 をver5.0として、PRごとにminorバージョンを上げる
* dependabotや、update README.md はカウントしないことにすると、 #107 がver5.11、これがver5.12になるはず
* 外部リンクのアイコン表示とスタイルの設定をExternalLinkコンポーネントに分離
=> バージョン表記を追加

app/play/page.tsx, package-lock.json, package.json
- **スタートボタンを2回押さないと始まらないことがあるバグを修正**
- **5.20.0**
=> スタートボタンを2回押さないと始まらないことがあるバグを修正

app/play/page.tsx, package-lock.json, package.json
- **小さい横長画面での表示を修正**
- **iOSでプレイ画面をスクロール可能に & スクロール後ゲーム画面がその位置にくるようにした**
- **5.21.0**
=> iOSでのプレイ画面の表示修正

app/common/footer.tsx, app/main/main.tsx, package-lock.json, package.json
- **footerなど微修正**
- **5.23.0**
=> footerなど微修正

app/common/box.tsx, app/edit/[cid]/page.tsx, app/layout.tsx, app/main/main.tsx, app/play/page.tsx, app/share/[cid]/page.tsx, package-lock.json, package.json
- **100vhを100dvhに変更**
- **playページのmarginを削除**
=> 100vhを100dvhに変更

app/api/brief/brief.ts, app/api/chartFile/[cid]/route.ts, app/api/newChartFile/route.ts, app/main/const.ts, app/main/play/page.tsx, package-lock.json, package.json
- **revalidateをcidごとに変更**
- **6.4.0**
=> revalidateをcidごとに変更

app/api/seqFile/[cid]/[lvIndex]/route.ts, package-lock.json, package.json
- **playCountを更新する時にキャッシュをrevaildateしていなかったのを修正**
- **6.5.0**
=> playCountを更新する時にキャッシュをrevaildateしていなかったのを修正

app/main/const.ts, package-lock.json, package.json
- **sample譜面リストを更新**
- **6.7.0**
=> sample譜面リストを更新

app/chartFormat/chart.ts, app/common/box.tsx, app/common/button.tsx, app/common/checkBox.tsx, app/common/footer.tsx, app/common/key.tsx, app/common/theme.tsx, app/play/bpmSign.tsx, app/play/messageBox.tsx, app/play/page.tsx, app/play/result.tsx, app/share/[cid]/playOption.tsx, package-lock.json, package.json, public/assets/cloud-black.svg, public/assets/cloud.svg, public/assets/note-white.svg, public/assets/note.svg, tailwind.config.ts
* Darkモードの背景色と文字色のバランスを変更
* Lightモードも文字色をblackからslate-300に変更
=> Darkモードの色味を変更

app/chartFormat/chart.ts, package-lock.json, package.json
- **ライトモードManiacの背景色をちょっと薄くした**
- **6.15.0**
=> ライトモードManiacの背景色をちょっと薄くした

package-lock.json, package.json, route/app.ts
=> ローカル環境での無限ループ修正

app/globals.css, app/main/main.tsx, package-lock.json, package.json
noto-sans-jpがなぜかlatestだとエラーを出していたので
=> フォントのバージョンを固定

package-lock.json, package.json, route/api/chartFile.ts
=> /api/chartFile のステータスコード修正

CHANGELOG_dev.md, app/common/box.tsx, app/errorPlaceholder/page.tsx, package-lock.json, package.json, route/app.ts, route/static.ts, vercel.json
fix #217 
* 404エラー時に404ページが表示されるようにした
* /share/cidのエラー時に返すerrorPlaceholderページを作成
* #220 で上書きしたpath-to-regexpではvercel devが動かなかったので、戻した
=> 404ページ、エラーページが表示されるようにする

.github/workflows/cf-purge.yaml
- **Cloudflareのキャッシュをpush時にクリアする**
- **CloudflareのCacheをpurgeする前に2分待つ**
=> CloudflareのCacheをpurgeする前に2分待つ

CHANGELOG_dev.md, package-lock.json, package.json, route/app.ts
cloudflareがAPIをキャッシュしないのはこれのせいな気がした﻿
=> apiにmiddlewareを適用しない

app/[locale]/play/musicArea.tsx, package-lock.json, package.json
=> musicAreaのoverflowの修正

CHANGELOG_dev.md, app/[locale]/common/version.ts, app/[locale]/play/clientPage.tsx, app/[locale]/play/score.tsx, app/i18n/en/changelog.mdx, app/i18n/ja/changelog.mdx, package-lock.json, package.json
* 100chainになったときに突然変わるのではなく、すこしずつ変化していくようにする
* FullChain中でない場合は100chainに到達しても色が変わらないようにする
=> chain数の色を黒/白から少しずつ変える

app/[locale]/common/title.ts, app/[locale]/edit/clientPage.tsx, app/[locale]/metadata.ts, package-lock.json, package.json
* 「譜面編集 - title (ID: )」のうしろに「 | Falling Nikochan」を追加
=> 編集画面のページタイトルを再度修正

CHANGELOG_dev.md, app/[locale]/common/loadingSlime.css, app/[locale]/common/loadingSlime.tsx, app/[locale]/common/version.ts, app/[locale]/edit/timingTab.tsx, app/[locale]/play/rhythmicalSlime.tsx, i18n/en/changelog.mdx, i18n/ja/changelog.mdx, package-lock.json, package.json, public/assets/slime2.svg
=> slimeの画像を2枚にした

CHANGELOG_dev.md, chartFormat/difficulty.ts, package-lock.json, package.json
=> 5個以上同時押しする譜面でレベルが20に張り付くのを防止

CHANGELOG_dev.md, package-lock.json, package.json, route/api/chartFile.ts
=> publishedがtrueに変わった場合に日時を更新する

CHANGELOG_dev.md, app/[locale]/edit/clientPage.tsx, app/[locale]/edit/timingTab.tsx, package-lock.json, package.json
bpmを変更してspeedも同時に変更される際にluaExecが2回連続で実行されてバグっていたのを修正﻿
=> bpmを変更する際bpmChangeとspeedChangeが同時に実行されるようにする

chartFormat/apiConfig.ts, package-lock.json, package.json
=> fileMaxSizeを大きめにした

CHANGELOG_dev.md, app/[locale]/globals.css, app/[locale]/layout.tsx, app/layout.tsx, bun.lock, package-lock.json, package.json
=> CDNを使わずフォントをインストールして埋め込む

package-lock.json, package.json, route/src/og.tsx
=> og画像はキャッシュすることにした

.github/workflows/node.js.yml, bun.lock, package-lock.json, package.json
#333 以降デプロイに失敗していて、vercelのバージョンが原因っぽい?ことがわかった
ローカルで変にoverrideしたvercelではなぜかnode_modulesの中身が正しく生成されないが、globalにvercel@latestをインストールすれば解決
=> localからvercelを削除し、globalインストールにする

eslint.config.js
=> fix cannot redefine typescript-eslint

api/index.js, route/serve-bun.ts, route/serve-local.ts, route/src/api/app.ts, route/src/index.ts
corsの引数で使うenvはimport時に実行されるコードなので実際に﻿envを使うファイルでdotenvを読み込まないと動作しない
=> dotenvを読み込むタイミングの修正

CHANGELOG_dev.md, chart/package.json, frontend/app/[locale]/common/redirectedWarning.tsx, frontend/app/[locale]/main/main.tsx, frontend/app/[locale]/share/placeholder/clientPage.tsx, frontend/package.json, i18n/en/main.js, i18n/ja/main.js, i18n/package.json, package-lock.json, route/package.json
=> redirected=1のときにwarningを表示する

.github/workflows/production.yml
=> deployの順番を変えcloudflareを先にする

CHANGELOG_dev.md, chart/package.json, frontend/app/[locale]/common/share.tsx, frontend/app/[locale]/common/title.ts, frontend/app/[locale]/common/version.ts, frontend/package.json, i18n/en/changelog.mdx, i18n/ja/changelog.mdx, i18n/package.json, package-lock.json, route/package.json
- shareリンクのパラメータ部分を薄い色で表示
- リンクをコピーした際タイトルを含める
=> shareリンクコピーボタンなどの変更

CHANGELOG_dev.md, chart/package.json, chart/src/lua/bpm.ts, chart/src/lua/edit.ts, chart/src/lua/note.ts, chart/src/lua/signature.ts, chart/src/lua/speed.ts, frontend/app/[locale]/common/mdxIcons.tsx, frontend/app/[locale]/edit/clientPage.tsx, frontend/app/[locale]/edit/luaTab.tsx, frontend/package.json, i18n/en/edit.js, i18n/en/guide/7-codeTab.mdx, i18n/ja/edit.js, i18n/ja/guide/7-codeTab.mdx, i18n/package.json, package-lock.json, route/package.json
- fix #56
- Aceのインスタンスを常時残しておくようにした fix #275
- AceEditorのpositionをabsoluteにし、annotationとmarkerでエラー時の表示と、小節線とカーソル位置の表示を実装
=> luaエディターの改良

chart/package.json, frontend/package.json, i18n/package.json, package-lock.json, route/package.json, worker/entry.ts, worker/package.json
- **swの更新確認時にキャッシュを使用しない**
- **ver10.6**
=> swの更新確認時にキャッシュを使用しない

chart/package.json, frontend/app/[locale]/share/placeholder/clientPage.tsx, frontend/app/[locale]/share/placeholder/sharedResult.tsx, frontend/package.json, i18n/package.json, package-lock.json, route/package.json, worker/package.json
- **shareページのUIのバグを修正**
- **ver10.8**
=> shareページのUIのバグを修正

CHANGELOG_dev.md, chart/package.json, frontend/app/[locale]/play/clientPage.tsx, frontend/package.json, i18n/package.json, package-lock.json, route/package.json, worker/package.json
* ユーザー入力のタイミングで鳴らさないとaudioが有効にならないsafariの対策で、スタートボタンを押した時にSEを鳴らすようにした
* キーを長押ししたときの繰り返し入力を無視するようにした
=> startボタンで音を鳴らす

CHANGELOG_dev.md, chart/package.json, frontend/app/[locale]/main/chartList.tsx, frontend/package.json, i18n/package.json, package-lock.json, route/package.json, worker/package.json
=> ChartListの表示を3列までにする

chart/package.json, frontend/app/[locale]/main/chartList.tsx, frontend/app/[locale]/main/latest/page.tsx, frontend/app/[locale]/main/shareInternal/clientPage.tsx, frontend/app/[locale]/main/shareModal.tsx, frontend/package.json, i18n/package.json, package-lock.json, route/package.json, worker/package.json
- shareBoxを開く際にbriefをfetchする close #448
- /main/latestで日付を表示 close #449
=> shareモーダル表示とChartListの微修正

CHANGELOG_dev.md, chart/package.json, chart/src/resultParams.ts, frontend/app/[locale]/play/clientPage.tsx, frontend/app/[locale]/play/gameLogic.ts, frontend/app/[locale]/play/result.tsx, frontend/app/[locale]/play/statusBox.tsx, frontend/app/[locale]/share/placeholder/sharedResult.tsx, frontend/package.json, i18n/package.json, package-lock.json, route/package.json, route/src/og/ogResult.tsx, route/src/og/style.ts, worker/package.json
=> Big音符が1つも無いときBig音符数表示とresultのBigボーナス表示はグレーアウトする

CHANGELOG_dev.md, chart/package.json, frontend/app/[locale]/clientPage.tsx, frontend/app/[locale]/common/bestScore.ts, frontend/app/[locale]/common/briefCache.ts, frontend/app/[locale]/common/levelBadge.tsx, frontend/app/[locale]/common/version.ts, frontend/app/[locale]/main/chartList.tsx, frontend/app/[locale]/main/latest/page.tsx, frontend/app/[locale]/main/play/clientPage.tsx, frontend/app/[locale]/main/popular/page.tsx, frontend/app/[locale]/main/recent/page.tsx, frontend/app/[locale]/play/clientPage.tsx, frontend/app/[locale]/share/placeholder/playOption.tsx, frontend/package.json, i18n/en/changelog.mdx, i18n/ja/changelog.mdx, i18n/package.json, package-lock.json, route/package.json, worker/package.json
close #467
ベストスコアデータの移行動作確認ok
ついでにbriefデータを圧縮して保存するのを試してみたが、大して変わらなかったのでやめた
=> bestScoreをlvHashごとの保存に変更

CHANGELOG_dev.md, chart/package.json, frontend/app/[locale]/play/se.ts, frontend/package.json, i18n/package.json, package-lock.json, route/package.json, worker/package.json
=> audioLatencyは最大値を使用する

CHANGELOG_dev.md, chart/package.json, frontend/package.json, i18n/package.json, package-lock.json, route/package.json, route/src/api/chartFile.ts, worker/package.json
=> 非表示の譜面の編集では日付を更新しないようにする

chart/package.json, frontend/app/[locale]/play/rhythmicalSlime.tsx, frontend/package.json, i18n/package.json, package-lock.json, route/package.json, worker/package.json
=> RhythmicalSlimeが非表示になるときサイズを維持

chart/package.json, frontend/app/[locale]/main/shareInternal/clientPage.tsx, frontend/app/[locale]/main/shareModal.tsx, frontend/app/[locale]/share/placeholder/clientPage.tsx, frontend/app/[locale]/share/placeholder/playOption.tsx, frontend/app/[locale]/share/placeholder/shareBox.tsx, frontend/package.json, i18n/package.json, package-lock.json, route/package.json, worker/package.json
- **recordのfetch中にloadingを表示**
- **ついでにベストスコアの表示を修正**
=> recordのfetch中にloadingを表示

CHANGELOG_dev.md, chart/package.json, frontend/app/[locale]/common/button.tsx, frontend/app/[locale]/common/pwaInstall.tsx, frontend/app/[locale]/common/theme.tsx, frontend/app/[locale]/play/bpmSign.tsx, frontend/app/[locale]/play/clientPage.tsx, frontend/app/[locale]/play/musicArea.tsx, frontend/app/[locale]/scale.tsx, frontend/package.json, i18n/package.json, package-lock.json, route/package.json, worker/package.json
ios16.0で発見したバグの修正
* cssのgradientが使えない環境で代わりの背景色を設定
* ipadのuserAgent認識を修正
* iosではYouTubeの音量を変更できないので、YouTube音量変更のinputを無効化
=> cssのgradientが使えない環境で代わりの背景色を設定

chart/package.json, frontend/app/[locale]/common/box.tsx, frontend/app/[locale]/common/button.tsx, frontend/app/[locale]/globals.css, frontend/app/[locale]/play/clientPage.tsx, frontend/app/[locale]/play/messageBox.tsx, frontend/app/[locale]/play/musicArea.tsx, frontend/app/[locale]/play/result.tsx, frontend/package.json, i18n/package.json, package-lock.json, route/package.json, worker/package.json
iPhoneでプレイ中にまれにテキスト選択の拡大表示が現れることがあり、onTouchStartとtouchEndにpreventDefault()を追加すると良いというのを見かけたのでやってみた
ほんとうに拡大表示が100%出ないようになったのかは不明
あと無反応はまったく改善しない
=> pointerDownにpreventDefaultを追加してみる

CHANGELOG_dev.md, bun.lock, chart/package.json, frontend/app/[locale]/play/clientPage.tsx, frontend/app/[locale]/play/fallingWindow.tsx, frontend/app/[locale]/play/messageBox.tsx, frontend/package.json, frontend/public/assets/ripple.svg, i18n/en/play.js, i18n/ja/play.js, i18n/package.json, package-lock.json, route/package.json, worker/package.json
close #526
﻿
playでの音符の描画をDOMで行うのではなく pixi.js を使ってWebGLで描画するようにした
=> pixi.jsで描画する

chart/package.json, frontend/package.json, i18n/package.json, package-lock.json, route/package.json, route/src/share.ts, worker/package.json
=> og:descriptionのエスケープ処理を追加

CHANGELOG_dev.md, chart/package.json, frontend/app/[locale]/common/version.ts, frontend/app/[locale]/main/links/clientPage.tsx, frontend/app/[locale]/main/version/clientPage.tsx, frontend/next.config.mjs, frontend/package.json, i18n/en/changelog.mdx, i18n/en/main.js, i18n/ja/changelog.mdx, i18n/ja/main.js, i18n/package.json, package-lock.json, route/package.json, worker/package.json
- **browserslistをtailwindの対応バージョンに合わせる**
- **対応ブラウザリストの表示を追加**
=> browserslistをtailwindの対応バージョンに合わせる

CHANGELOG_dev.md, chart/package.json, chart/src/legacy/seq11.ts, chart/src/legacy/seq6.ts, chart/src/legacy/seq7.ts, frontend/app/[locale]/common/version.ts, frontend/app/[locale]/play/fallingWindow.tsx, frontend/package.json, i18n/en/changelog.mdx, i18n/ja/changelog.mdx, i18n/package.json, package-lock.json, route/package.json, worker/package.json
- Applies fade-in & fade-out to notes.
- Smooth-out note appearance transition when enter/exit the scene.
<hr>
https://github.com/user-attachments/assets/e7adf4cb-64cb-4016-a782-143922bbcfe7
https://github.com/user-attachments/assets/817dd514-2b8c-4096-a23c-7c226f5a0659
<hr>
https://github.com/user-attachments/assets/d54b3ae5-0134-4fdc-ac42-ae05d7cdeeec
https://github.com/user-attachments/assets/cadb28b6-63b0-4eba-890b-bcab05a5077a
=> Fading notes

chart/package.json, frontend/app/[locale]/edit/clientPage.tsx, frontend/app/[locale]/edit/timeBar.tsx, frontend/package.json, i18n/package.json, package-lock.json, route/package.json, worker/package.json
=> snapDivider変更時にもtimebarBeginStepとcurrentStepが更新されるようにする

CHANGELOG_dev.md, chart/package.json, frontend/app/[locale]/common/version.ts, frontend/app/[locale]/edit/clientPage.tsx, frontend/app/[locale]/edit/luaTab.tsx, frontend/package.json, i18n/en/changelog.mdx, i18n/en/guide/7-codeTab.mdx, i18n/ja/changelog.mdx, i18n/ja/guide/7-codeTab.mdx, i18n/package.json, package-lock.json, route/package.json, worker/package.json
- ReactAceのsearchBoxを有効化 (close #579)
- edit画面をスクロールした際にreact-aceの位置を更新する
=> codeエディターの修正

chart/package.json, frontend/app/[locale]/clientPage.tsx, frontend/app/[locale]/common/box.tsx, frontend/app/[locale]/common/festival.tsx, frontend/app/[locale]/common/pwaInstall.tsx, frontend/app/[locale]/common/redirectedWarning.tsx, frontend/app/[locale]/main/links/clientPage.tsx, frontend/package.json, i18n/en/main.js, i18n/ja/main.js, i18n/package.json, package-lock.json, route/package.json, worker/package.json
- **WarningBoxをコンポーネントにまとめた**
- **festivalのページへもどるリンクを実装**
=> festivalのページへもどるリンクを実装

CHANGELOG_dev.md, chart/package.json, frontend/package.json, i18n/package.json, package-lock.json, route/package.json, route/src/sitemap.ts, worker/package.json
=> sitemapをgzip圧縮しない

chart/package.json, frontend/package.json, i18n/package.json, package-lock.json, route/package.json, route/src/share.ts, worker/package.json
=> shareページでの絵文字のエスケープを修正

CHANGELOG_dev.md, chart/package.json, frontend/app/[locale]/common/footer.tsx, frontend/app/[locale]/common/pwaInstall.tsx, frontend/package.json, i18n/package.json, package-lock.json, route/package.json, worker/entry.ts, worker/package.json
- **serviceworkerの更新時にプログレスバーを表示する**
- **pwaのステータス表示処理をfooterからProviderに移動**
=> serviceworkerの更新時にプログレスバーを表示する

CHANGELOG_dev.md, chart/package.json, frontend/app/[locale]/common/changeLog.tsx, frontend/app/[locale]/common/footer.tsx, frontend/app/[locale]/layout.tsx, frontend/package.json, i18n/en/main.js, i18n/ja/main.js, i18n/package.json, package-lock.json, route/package.json, worker/package.json
=> changelogをページ遷移せずに重ねて表示

CHANGELOG_dev.md, chart/package.json, frontend/app/[locale]/clientPage.tsx, frontend/app/[locale]/common/changeLog.tsx, frontend/app/[locale]/common/delayedDisplayState.ts, frontend/app/[locale]/common/shareLinkAndImage.tsx, frontend/app/[locale]/common/sharePageModal.tsx, frontend/app/[locale]/common/titleLogo.tsx, frontend/app/[locale]/main/play/clientPage.tsx, frontend/app/[locale]/play/fallingWindow.tsx, frontend/app/[locale]/play/messageBox.tsx, frontend/app/[locale]/share/placeholder/clientPage.tsx, frontend/package.json, i18n/package.json, package-lock.json, route/package.json, worker/package.json
- **アニメーション用の遅延setStateをカスタムフックにまとめた**
- **changelogにshadowを追加**
=> アニメーション用の遅延setStateをカスタムフックにまとめた

api/index.js, chart/package.json, frontend/package.json, i18n/dynamic.js, i18n/package.json, i18n/staticMin.js, package-lock.json, route/package.json, route/serve-bun.ts, route/serve-cf.js, route/serve-local.ts, route/src/env.ts, route/src/index.ts, route/src/redirect.ts, route/src/share.ts, route/tests/api/init.ts, worker/entry.ts, worker/package.json
=> accept-languageがja-JPの場合の処理を追加

chart/package.json, frontend/app/[locale]/clientPage.tsx, frontend/app/[locale]/main/chartList.tsx, frontend/app/[locale]/main/play/clientPage.tsx, frontend/package.json, i18n/package.json, package-lock.json, route/package.json, worker/package.json
- **譜面リストの表示項目数を修正**
- **スクロールの処理を修正**
=> 譜面リストの表示項目数とスクロールを修正

CHANGELOG_dev.md, chart/package.json, frontend/app/[locale]/share/placeholder/clientPage.tsx, frontend/package.json, i18n/package.json, package-lock.json, route/package.json, worker/entry.ts, worker/package.json
- **キャッシュがない状態でshareを開くと空ページになるバグを修正**
- **shareページのタイトル強制上書き**
=> キャッシュがない状態でshareを開くと空ページになるバグを修正
