app/common/box.tsx, app/common/footer.tsx, app/common/youtube.tsx, app/edit/[cid]/page.tsx, app/layout.tsx, app/main/main.tsx, app/play/[cid]/bpmSign.tsx, app/play/[cid]/messageBox.tsx, app/play/[cid]/page.tsx, app/play/[cid]/rhythmicalSlime.tsx, app/play/[cid]/score.tsx, app/play/[cid]/statusBox.tsx, app/scale.tsx, app/share/[cid]/page.tsx
* ブラウザのwidthにあわせてbody全体をscaleして一定のサイズにするというでっち上げ実装をやめてちゃんとレスポンシブな処理をした
* スマホ横表示 (横長で画面が小さい時) にstatusBoxの表示をするスペースがないのでresult時のみ表示するようにした
* Box の背景にblur追加したりした
=> body全体をscaleせずにレスポンシブ対応

app/play/[cid]/gameLogic.ts
- chainBonusに判定の倍率がかからないようにした (FullChainなら判定結果によらずchainBonus=30)
- 判定基準を見直そうとした (cf.#12)
- なんとなく Bad -120ms→-150ms に拡大してみた
=> score bonus

app/chartFormat/lua/edit.ts, app/edit/[cid]/fallingWindow.tsx, app/edit/[cid]/noteTab.tsx, app/edit/[cid]/page.tsx, app/edit/[cid]/timingTab.tsx
* 1つのluaコマンドに複数の音符が対応していた時それを削除した時の挙動を修正
* codeタブを開いている時FallingWindowから音符を編集できないようにした
* luaLine=null のデータに対してBPM編集、Speed編集、Note編集をdisableしメッセージを出すようにした
=> 編集できない時各種編集機能をdisable

app/common/footer.tsx, app/main/chartList.tsx, app/main/edit/page.tsx, app/main/main.tsx, app/main/play/page.tsx, app/main/policies/page.tsx
* aboutページ以外の文章を wbr/ での改行をやめて両端揃え表示
* PC表示のとき曲名の横に作曲者表示
* GitHubへのリンクを新しいタブで開くように
* フッターのbuild表示をcommit履歴へのリンクに
* domainなど一部のテキストを小さくした
=> メインページのテキストなどいろいろ修正

package.json
turbopackが有効だとwasmoonのimportに失敗する
=> turbopackを無効にする

app/api/chartFile/[cid]/route.ts, app/common/checkBox.tsx, app/common/input.tsx, app/edit/[cid]/metaTab.tsx, app/edit/[cid]/page.tsx, app/edit/[cid]/timeBar.tsx, app/main/edit/page.tsx, package-lock.json, package.json
- iOSでID入力して譜面編集画面が開かないので、ID入力後に開くボタンが表示されるようにした
- 編集画面を開いて最初は「パスワードが間違っています」を表示しないようにした
- dev環境でのみパスワードのチェックをスキップするようにした (iOSがhttpでcryptoを使えないので)
- lightテーマのチェックボックスの色を修正
=> 譜面編集画面を開く挙動を修正

app/api/brief/brief.ts, package-lock.json, package.json
再生数などが変わってもsample譜面のリストが変わることはないので、 /main/play はrevalidateせずSSGにする (#146)
=> /main/play をrevalidateしない

.github/workflows/node.js.yml
#234 でlockfileを更新してpushするciを作ったが、github actionがpushしたコミットに対してはCIが自動で走らないので、手動でdispatchすればいいと思ったが、意味なかった
=> 手動でworkflowを動かしてもPRのマージ条件には入らないらしい

CHANGELOG_dev.md, app/[locale]/edit/clientPage.tsx, app/[locale]/edit/metaTab.tsx, package-lock.json, package.json
* metaタブの「パスワードを保存」のチェックが勝手に外れるバグを修正
* 「パスワードを保存」のチェックがないとき<del>アプリが本当に今のパスワードを忘れて</del>上書き保存ができなくなるバグを修正
* /ja/edit?cid=new から /edit?cid=123456 へリダイレクトしてしまう(localeがない)のを修正
=> 譜面を新規作成したときのパスワード周りの処理を修正

CHANGELOG_dev.md, app/[locale]/edit/noteTab.tsx, chartFormat/legacy/seq7.ts, chartFormat/legacy/seq8.ts, chartFormat/lua/exec.ts, package-lock.json, package.json
- 負の速度を編集できないバグの修正 (fix #295)
- vyまたはspeedが負のときの音符出現位置の計算を修正
- noteタブでもvyに負の値を指定可能に
- LoadChart7削除(もう使っていないので)
=> 負の速度に関する計算を修正

CHANGELOG_dev.md, package-lock.json, package.json, route/app.ts
XSS対策のため。エスケープする必要のある文字を列挙するのは自信がなかったので、すべての文字をエスケープすることにした
=> shareページのタイトルをエスケープ

.github/workflows/node.js.yml, CHANGELOG_dev.md, README.md, chart/package.json, frontend/package.json, i18n/en/error.js, i18n/ja/error.js, i18n/package.json, package-lock.json, package.json, route/package.json, route/src/api/chart.ts, route/src/api/chartFile.ts, route/src/api/newChartFile.ts, route/src/api/playFile.ts, route/src/env.ts, route/src/index.ts, route/tests/api/brief.spec.ts, route/tests/api/chartFile.get.spec.ts, route/tests/api/chartFile.post.spec.ts, route/tests/api/hashPasswd.spec.ts, route/tests/api/init.ts, route/tests/api/latest.spec.ts, route/tests/api/newChartFile.post.spec.ts, route/tests/api/playFile.spec.ts, route/tsconfig.json
* apiのテストを書いた `bun route:test`
* messagepackを返すAPIでContent-Typeを設定するようにした
* cidを受け取るAPIでcidが不正な場合400を返すようにした
* API_ENV とは別に /api/newChartFile のratelimitの有無を切り替える API_NO_RATELIMIT 環境変数を追加
* ciにテストの実行を追加、さらにjob間の依存関係を少し変更し効率化
=> apiのtestを書く

.gitignore, CHANGELOG_dev.md, chart/package.json, chart/src/luaExec/exec.ts, frontend/app/[locale]/edit/luaTab.tsx, frontend/app/[locale]/edit/metaTab.tsx, frontend/initAssets.js, frontend/package.json, i18n/package.json, package-lock.json, package.json, route/package.json
今まではwasmoonのLuaFactory()内でCDNからglue.wasmをfetchしていたらしいが、node_modulesからpublic/assets/にコピーしそれを使うようにする
(よく考えたらYouTubeEmbedにインターネットが要るのだからどのみちインターネットなしで動かないことに変わりはないのでは...)
=> wasmoonのwasmをassetsに入れてローカルでも使えるようにする

CHANGELOG_dev.md, bun.lock, chart/package.json, frontend/package.json, i18n/package.json, package-lock.json, route/package.json
Reverts na-trium-144/falling-nikochan#371
@fontsource/merriweatherパッケージを5.2.5→5.2.6にアップデートすると明らかに見た目が変わってるんだけどどういうこと??
5.2.5
5.2.6
=> Revert "Bump @fontsource/merriweather from 5.2.5 to 5.2.6"

bun.lock, chart/package.json, frontend/app/[locale]/edit/luaTab.tsx, frontend/package.json, i18n/package.json, package-lock.json, route/package.json
#421 の続きで、
グローバル変数をいじらずにremote-web-workerパッケージのパッチを使うようにすることでCDNを利用できるようになったが、auto-mergeを解除するのが間に合わなかった
=> 別ドメインのworkerを読み込めずエラーになっていたのを修正

CHANGELOG_dev.md, chart/package.json, frontend/app/[locale]/metadata.ts, frontend/app/[locale]/share/placeholder/clientPage.tsx, frontend/app/[locale]/share/placeholder/page.tsx, frontend/app/[locale]/share/placeholder/shareBox.tsx, frontend/package.json, i18n/package.json, package-lock.json, route/package.json, route/src/share.ts, worker/package.json
#369 でassetsのURLの都合?でshareページのbodyをSSRせずクライアント側でfetchする仕様に変更していたが、遅いのでやっぱりSSRにする
jsコードを書き換えずにbriefデータを渡すため、metaタグを利用
=> shareページをmetaタグ使って再度SSRに戻した

CHANGELOG_dev.md, chart/package.json, frontend/app/[locale]/play/clientPage.tsx, frontend/app/[locale]/play/fallingWindow.tsx, frontend/app/[locale]/play/se.ts, frontend/package.json, i18n/package.json, package-lock.json, route/package.json, worker/package.json
* play画面のフレームレートができるだけ一定になるように修正
* displayNoteの計算をrequestAnimationFrameではなくrender時に行う
* Revert "audioLatencyは最大値を使用する (#496)"
どうしてもAndroidで音符の表示が揺れる。#496 は関係なさそうだったのでrevert。シンプルに性能が足りていなくてフレームレートが落ちているだけな気もするが、なんでそんなに重くなっているのかがわからん
=> フレームレートの安定化

CHANGELOG_dev.md, chart/package.json, frontend/app/[locale]/edit/clientPage.tsx, frontend/app/[locale]/edit/metaTab.tsx, frontend/app/[locale]/main/chartList.tsx, frontend/app/[locale]/main/edit/clientPage.tsx, frontend/app/[locale]/play/clientPage.tsx, frontend/package.json, i18n/en/error.js, i18n/ja/error.js, i18n/package.json, package-lock.json, route/package.json, route/serve-bun.ts, route/serve-local.ts, route/src/api/brief.ts, route/src/error.ts, route/src/og/app.ts, route/tests/api/init.ts, worker/package.json
close #500
close #432
﻿
* /api/latest や popular へのリクエストがエラーになったときstatusとmessageを表示する
* serviceWorkerがAPIへのfetchに失敗した場合502を返す
* /share が/api/briefへのアクセス中に発生したエラーステータスをそのまま返す
=> fetchエラーの処理を修正

CHANGELOG_dev.md, chart/package.json, frontend/app/[locale]/common/version.ts, frontend/app/[locale]/play/musicArea.tsx, frontend/app/[locale]/play/statusBox.tsx, frontend/package.json, i18n/en/changelog.mdx, i18n/ja/changelog.mdx, i18n/package.json, package-lock.json, route/package.json, worker/package.json
- 音符数表示をpcは1の桁中央揃え/モバイルは中央揃えに変更
- musicAreaにveryLargeTitleモードを追加 (iPad用)
=> 音符数表示とmusicAreaのcssの変更

CHANGELOG_dev.md, chart/package.json, frontend/app/[locale]/common/version.ts, frontend/app/[locale]/play/fallingWindow.tsx, frontend/package.json, i18n/en/changelog.mdx, i18n/ja/changelog.mdx, i18n/package.json, package-lock.json, route/package.json, worker/package.json
objectURLよりbase64のほうが若干速そうな気がした
Androidでの動作がちょっと軽くなった (けど、完全に解決したわけではない)
=> play中の画像アセットを音符1個ごとにfetchしないようbase64のdataURLに変更
